#
# 随机生成一个密码
# docker exec -it alist ./alist admin random
# 手动设置一个密码,`NEW_PASSWORD`是指你需要设置的密码
# docker exec -it alist ./alist admin set NEW_PASSWORD
#
version: '3.8'
services:
    alist:
        container_name: alist-6244
        image: xhofe/alist
        restart: unless-stopped
        volumes:
            - /opt/docker/alist/data:/opt/alist/data
            - /opt/docker/alist/storage:/opt/alist/storage
            - /opt/docker/aria2/downloads:/opt/alist/storage/downloads
        # ports:
        #    - 6244:5244
        network_mode: host
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
            - TZ=Asia/Shanghai
