# jupyter 
services:
  jupyter:
    image: quay.io/jupyter/pytorch-notebook:latest
    container_name: jupyter
    restart: unless-stopped
    environment:
      - JUPYTER_TOKEN=0B253CDA-DC7A-4370-8B95-C0156475BAC8
    ports:
      - 6088:6088
    volumes:
      - /opt/docker/jupyter/notebooks:/home/jovyan/work
