version: '3.8'
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve
    restart: unless-stopped
    ports:
      - 6212:5212
    volumes:
      - /opt/docker/cloudreve/uploads:/cloudreve/uploads
      - /opt/docker/cloudreve/conf.ini:/cloudreve/conf.ini
      - /opt/docker/cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - /opt/docker/cloudreve/avatar:/cloudreve/avatar
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022