#
# 随机生成一个密码
# docker exec -it alist ./alist admin random
# 手动设置一个密码,`NEW_PASSWORD`是指你需要设置的密码
# docker exec -it alist ./alist admin set NEW_PASSWORD
#
version: '3.8'
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /opt/docker/nextcloud/config:/config
      - /opt/docker/nextcloud/data:/data
    ports:
      - 6443:443
      - 6080:80
    restart: unless-stopped
