# xray 
version: '3.8'
services:
  v2fly:
    image: v2fly/v2fly-core:latest
    container_name: v2fly
    restart: unless-stopped
    network_mode: host
    ports:
      - 6403:443
      - 6480:80
    volumes:
      - /opt/docker/v2fly/config.json:/etc/v2fly/config.json
    command: v2fly -config=/etc/v2fly/config.json
