services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - CHROME_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - /opt/docker/chromium/config:/config
    ports:
      - 63000:3000
      - 63001:3001
    shm_size: "2gb"
    restart: unless-stopped