# jupyter 
services:
  jupyter:
    image: quay.io/jupyter/pytorch-notebook:latest
    container_name: jupyter
    restart: unless-stopped
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=
      - JUPYTER_PASSWORD=P@ssw0rd
    ports:
      - 6088:8888
    volumes:
      - /opt/docker/jupyter/notebooks:/home/jovyan/work
      - /opt/docker/jupyter/jupyter_notebook_config.py:/etc/jupyter/jupyter_notebook_config.py
