# xray 
services:
  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    network_mode: host
    # use host not port mapping
    # ports: 
    #  - 6443:6443
    volumes:
      - /opt/docker/xray:/etc/xray
    logging:
      driver: none
