# vscode 
services:
  vscode:
    image: mcr.microsoft.com/vscode/devcontainers/base:dev-bullseye
    container_name: vscode
    restart: unless-stopped
    ports:
      - 6300:3000
    volumes:
      - /opt/docker/vscode/workspace:/workspace
