# xray 
version: '3.8'
services:
  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    network_mode: host
    ports:
      - 6443:6443
    volumes:
      - /opt/docker/xray/config.json:/etc/xray/config.json
    command: xray -config=/etc/xray/config.json
